name: Build XD Drive Studio

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: windows-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build EXE
      run: |
        pyinstaller xd_drive_studio.spec --noconfirm

    - name: Install Inno Setup
      run: |
        choco install innosetup -y

    - name: Build Installer
      run: |
        "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" installer.iss

    - name: Upload Installer
      uses: actions/upload-artifact@v4
      with:
        name: XD_Drive_Studio_Setup
        path: Output/XD_Drive_Studio_Setup.exe
